"""add equipment_type origin destination to call_logs

Revision ID: a7d1bbe5373d
Revises: 2956ccba6703
Create Date: 2026-05-04 14:06:38.039421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d1bbe5373d'
down_revision: Union[str, Sequence[str], None] = '2956ccba6703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('equipment_type', sa.String(), nullable=True))
    op.add_column('call_logs', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('call_logs', sa.Column('destination', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'destination')
    op.drop_column('call_logs', 'origin')
    op.drop_column('call_logs', 'equipment_type')
    # ### end Alembic commands ###
